plugins {
  id 'java-library'
}

dependencies {
  implementation libs.jakarta.inject.api
  implementation libs.sonar.plugin.api
  implementation mn.jsr305
  implementation mn.jackson.core
  implementation mn.jackson.databind
  implementation mn.jackson.dataformat.yaml

  testImplementation libs.junit.pioneer
  testImplementation mn.assertj.core
  testImplementation mn.logback.classic
  testImplementation mn.logback.core
  testImplementation mn.micronaut.test.junit5
  testImplementation mn.mockito.core
  testImplementation mn.mockito.junit.jupiter

  testRuntimeOnly libs.junit.engine
}

ext {
  release = project.hasProperty('release') && project.getProperty('release')
  buildNumber = System.getProperty("buildNumber")
}
// Replaces the version defined in sources, usually x.y-SNAPSHOT, by a version identifying the build.
if (version.endsWith('-SNAPSHOT') && ext.buildNumber != null) {
  def versionSuffix = (version.toString().count('.') == 1 ? ".0.${ext.buildNumber}" : ".${ext.buildNumber}")
  version = version.replace('-SNAPSHOT', versionSuffix)
}

publishing {
  publications {
    service(MavenPublication) {
      from components.java
    }
  }
}

artifactoryPublish {
  skip = false
  publications(publishing.publications.service)
}

// publish a Java 17-compatible library
java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(17)
  }
}

test {
  useJUnitPlatform()
}
