name: Release

on:
  release:
    types:
      - published

jobs:
  get-visibility:
    runs-on: github-ubuntu-latest-s
    outputs:
      visibility: ${{ steps.determine-visibility.outputs.visibility }}
    steps:
      - name: Determine release visibility
        id: determine-visibility
        run: |
          echo "visibility=${{ startsWith(github.event.release.tag_name, 'private-') && 'private' || 'public' }}" >> "$GITHUB_OUTPUT"

  release:
    needs: get-visibility
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@v6
    with:
      mavenCentralSync: ${{ needs.get-visibility.outputs.visibility == 'public' }}
      publicRelease: ${{ needs.get-visibility.outputs.visibility == 'public' }}
